# This provides us with GCC binary support so we can run bash
language: generic

sudo: required

script:
  - ./build.sh

before_deploy:
  - export image_name="`echo *.iso`"
  - cat *.iso > "/home/travis/${image_name}"

deploy:
    on:
      branch: master

